name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake g++ googletest

    - name: Configure CMake
      run: cmake -S . -B build

    - name: Build
      run: cmake --build build

    - name: Run tests
      run: |
        ./build/lab1/test_lab1
        ./build/lab2/test_lab2
        ./build/lab3/test_lab3
        ./build/lab4/test_lab4
        ./build/lab5/test_lab5
        ./build/lab6/test_lab6
        ./build/lab7/test_lab7